export const OSCARS_SEED = [
  {
    "watched": true,
    "watched_date": null,
    "title": "Retirement Plan",
    "type": "Short",
    "runtime_helper": "7 min",
    "runtime_helper_2": "7min",
    "runtime": "7min",
    "rating_1_10": 7.0,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Retirement%20Plan",
    "imdb_url": "https://www.imdb.com/find/?q=Retirement%20Plan",
    "id": 1
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Forevergreen",
    "type": "Short",
    "runtime_helper": "13 min",
    "runtime_helper_2": "13min",
    "runtime": "13min",
    "rating_1_10": 7.0,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Forevergreen",
    "imdb_url": "https://www.imdb.com/find/?q=Forevergreen",
    "id": 2
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Jane Austen's Period Drama",
    "type": "Short",
    "runtime_helper": "13 min",
    "runtime_helper_2": "13min",
    "runtime": "13min",
    "rating_1_10": 7.0,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Live Action Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Jane%20Austen%27s%20Period%20Drama",
    "imdb_url": "https://www.imdb.com/find/?q=Jane%20Austen%27s%20Period%20Drama",
    "id": 3
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "The Three Sisters",
    "type": "Short",
    "runtime_helper": "14 min",
    "runtime_helper_2": "14min",
    "runtime": "14min",
    "rating_1_10": 3.0,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Three%20Sisters",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Three%20Sisters",
    "id": 4
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Butterfly",
    "type": "Short",
    "runtime_helper": "15 min",
    "runtime_helper_2": "15min",
    "runtime": "15min",
    "rating_1_10": 7.0,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Butterfly",
    "imdb_url": "https://www.imdb.com/find/?q=Butterfly",
    "id": 5
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Perfectly a Strangeness",
    "type": "Short",
    "runtime_helper": "15 min",
    "runtime_helper_2": "15min",
    "runtime": "15min",
    "rating_1_10": null,
    "director_s": "Alison McAlpine",
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Documentary Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Perfectly%20a%20Strangeness",
    "imdb_url": "https://www.imdb.com/find/?q=Perfectly%20a%20Strangeness",
    "id": 6
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "The Girl Who Cried Pearls",
    "type": "Short",
    "runtime_helper": "17 min",
    "runtime_helper_2": "17min",
    "runtime": "17min",
    "rating_1_10": 7.0,
    "director_s": "Chris Lavis, Maciek Szczerbowski",
    "country": "Canada",
    "nominations_number": 1,
    "nominated_categories": "Animated Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Girl%20Who%20Cried%20Pearls",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Girl%20Who%20Cried%20Pearls",
    "id": 7
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Singers",
    "type": "Short",
    "runtime_helper": "18 min",
    "runtime_helper_2": "18min",
    "runtime": "18min",
    "rating_1_10": null,
    "director_s": null,
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Live Action Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "https://www.bilibili.com/video/BV1yoFMzjE3G/?spm_id_from=333.788.recommend_more_%20video.0&trackid=web_related_0.router-related-2481894-52kq4.1770060780511.35",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Singers",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Singers",
    "id": 8
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "A Friend of Dorothy",
    "type": "Short",
    "runtime_helper": "21 min",
    "runtime_helper_2": "21min",
    "runtime": "21min",
    "rating_1_10": null,
    "director_s": null,
    "country": "United Kingdom",
    "nominations_number": 1,
    "nominated_categories": "Live Action Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Disney+",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=A%20Friend%20of%20Dorothy",
    "imdb_url": "https://www.imdb.com/find/?q=A%20Friend%20of%20Dorothy",
    "id": 9
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Butcher's Stain",
    "type": "Short",
    "runtime_helper": "26 min",
    "runtime_helper_2": "26min",
    "runtime": "26min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Live Action Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "https://www.bilibili.com/video/BV1YakbBGEoi/?spm_id_from=333.337.search-card.all.click",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Butcher%27s%20Stain",
    "imdb_url": "https://www.imdb.com/find/?q=Butcher%27s%20Stain",
    "id": 10
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Devil Is Busy",
    "type": "Short",
    "runtime_helper": "31 min",
    "runtime_helper_2": "31min",
    "runtime": "31min",
    "rating_1_10": null,
    "director_s": "Geeta Gandbhir",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Documentary Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "HBO max",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Devil%20Is%20Busy",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Devil%20Is%20Busy",
    "id": 11
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "All the Empty Rooms",
    "type": "Short",
    "runtime_helper": "33 min",
    "runtime_helper_2": "33min",
    "runtime": "33min",
    "rating_1_10": null,
    "director_s": "Joshua Seftel",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Documentary Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=All%20the%20Empty%20Rooms",
    "imdb_url": "https://www.imdb.com/find/?q=All%20the%20Empty%20Rooms",
    "id": 12
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Children No More: \"Were and Are Gone\"",
    "type": "Short",
    "runtime_helper": "36 min",
    "runtime_helper_2": "36min",
    "runtime": "36min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Documentary Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Children%20No%20More%3A%20%22Were%20and%20Are%20Gone%22",
    "imdb_url": "https://www.imdb.com/find/?q=Children%20No%20More%3A%20%22Were%20and%20Are%20Gone%22",
    "id": 13
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Two People Exchanging Saliva",
    "type": "Short",
    "runtime_helper": "36 min",
    "runtime_helper_2": "36min",
    "runtime": "36min",
    "rating_1_10": null,
    "director_s": "Natalie Musteata, Alexandre Singh, fr",
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Live Action Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "https://www.youtube.com/watch?v=RuOEEu--j2Y",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Two%20People%20Exchanging%20Saliva",
    "imdb_url": "https://www.imdb.com/find/?q=Two%20People%20Exchanging%20Saliva",
    "id": 14
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Armed Only with a Camera: The Life and Death of Brent Renaud",
    "type": "Short",
    "runtime_helper": "37 min",
    "runtime_helper_2": "37min",
    "runtime": "37min",
    "rating_1_10": null,
    "director_s": "Brent Renaud",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Documentary Short Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "HBO max",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Armed%20Only%20with%20a%20Camera%3A%20The%20Life%20and%20Death%20of%20Brent%20Renaud",
    "imdb_url": "https://www.imdb.com/find/?q=Armed%20Only%20with%20a%20Camera%3A%20The%20Life%20and%20Death%20of%20Brent%20Renaud",
    "id": 15
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Viva Verdi!",
    "type": "Feature",
    "runtime_helper": "77 min",
    "runtime_helper_2": "77min",
    "runtime": "1h 17min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Music (Original Song)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Viva%20Verdi%21",
    "imdb_url": "https://www.imdb.com/find/?q=Viva%20Verdi%21",
    "id": 16
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Little Am\u00e9lie or the Character of Rain",
    "type": "Feature",
    "runtime_helper": "78 min",
    "runtime_helper_2": "78min",
    "runtime": "1h 18min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Little%20Am%C3%A9lie%20or%20the%20Character%20of%20Rain",
    "imdb_url": "https://www.imdb.com/find/?q=Little%20Am%C3%A9lie%20or%20the%20Character%20of%20Rain",
    "id": 17
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Arco",
    "type": "Feature",
    "runtime_helper": "82 min",
    "runtime_helper_2": "82min",
    "runtime": "1h 22min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Arco",
    "imdb_url": "https://www.imdb.com/find/?q=Arco",
    "id": 18
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Voice of Hind Rajab",
    "type": "Feature",
    "runtime_helper": "89 min",
    "runtime_helper_2": "89min",
    "runtime": "1h 29min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "International Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Voice%20of%20Hind%20Rajab",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Voice%20of%20Hind%20Rajab",
    "id": 19
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Elio",
    "type": "Feature",
    "runtime_helper": "90 min",
    "runtime_helper_2": "90min",
    "runtime": "1h 30min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Animated Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Elio",
    "imdb_url": "https://www.imdb.com/find/?q=Elio",
    "id": 20
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Mr. Nobody against Putin",
    "type": "Feature",
    "runtime_helper": "90 min",
    "runtime_helper_2": "90min",
    "runtime": "1h 30min",
    "rating_1_10": null,
    "director_s": "David Borenstein",
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Documentary Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Mr.%20Nobody%20against%20Putin",
    "imdb_url": "https://www.imdb.com/find/?q=Mr.%20Nobody%20against%20Putin",
    "id": 21
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Diane Warren: Relentless",
    "type": "Feature",
    "runtime_helper": "91 min",
    "runtime_helper_2": "91min",
    "runtime": "1h 31min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Music (Original Song)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Diane%20Warren%3A%20Relentless",
    "imdb_url": "https://www.imdb.com/find/?q=Diane%20Warren%3A%20Relentless",
    "id": 22
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Cutting through Rocks",
    "type": "Feature",
    "runtime_helper": "95 min",
    "runtime_helper_2": "95min",
    "runtime": "1h 35min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Documentary Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Cutting%20through%20Rocks",
    "imdb_url": "https://www.imdb.com/find/?q=Cutting%20through%20Rocks",
    "id": 23
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "KPop Demon Hunters",
    "type": "Feature",
    "runtime_helper": "95 min",
    "runtime_helper_2": "95min",
    "runtime": "1h 35min",
    "rating_1_10": 7.0,
    "director_s": "Maggie Kang, Chris Appelhans",
    "country": "United States",
    "nominations_number": 2,
    "nominated_categories": "Animated Feature Film; Music (Original Song)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=KPop%20Demon%20Hunters",
    "imdb_url": "https://www.imdb.com/find/?q=KPop%20Demon%20Hunters",
    "id": 24
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Perfect Neighbor",
    "type": "Feature",
    "runtime_helper": "97 min",
    "runtime_helper_2": "97min",
    "runtime": "1h 37min",
    "rating_1_10": null,
    "director_s": "Geeta Gandbhir",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Documentary Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "PirateBay",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Perfect%20Neighbor",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Perfect%20Neighbor",
    "id": 25
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Blue Moon",
    "type": "Feature",
    "runtime_helper": "100 min",
    "runtime_helper_2": "100min",
    "runtime": "1h 40min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 2,
    "nominated_categories": "Actor in a Leading Role; Writing (Original Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "PC",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Blue%20Moon",
    "imdb_url": "https://www.imdb.com/find/?q=Blue%20Moon",
    "id": 26
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Train Dreams",
    "type": "Feature",
    "runtime_helper": "103 min",
    "runtime_helper_2": "103min",
    "runtime": "1h 43min",
    "rating_1_10": 8.0,
    "director_s": null,
    "country": null,
    "nominations_number": 4,
    "nominated_categories": "Best Picture; Cinematography; Music (Original Song); Writing (Adapted Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "PC",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Train%20Dreams",
    "imdb_url": "https://www.imdb.com/find/?q=Train%20Dreams",
    "id": 27
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Come See Me in the Good Light",
    "type": "Feature",
    "runtime_helper": "104 min",
    "runtime_helper_2": "104min",
    "runtime": "1h 44min",
    "rating_1_10": null,
    "director_s": null,
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Documentary Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Come%20See%20Me%20in%20the%20Good%20Light",
    "imdb_url": "https://www.imdb.com/find/?q=Come%20See%20Me%20in%20the%20Good%20Light",
    "id": 28
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "It Was Just an Accident",
    "type": "Feature",
    "runtime_helper": "105 min",
    "runtime_helper_2": "105min",
    "runtime": "1h 45min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 2,
    "nominated_categories": "International Feature Film; Writing (Original Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/It_Was_Just_an_Accident",
    "imdb_url": "https://www.imdb.com/title/tt31120368/",
    "id": 29
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Zootopia 2",
    "type": "Feature",
    "runtime_helper": "108 min",
    "runtime_helper_2": "108min",
    "runtime": "1h 48min",
    "rating_1_10": null,
    "director_s": "Jared Bush, Byron Howard",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Animated Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Zootopia%202",
    "imdb_url": "https://www.imdb.com/find/?q=Zootopia%202",
    "id": 30
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Ugly Stepsister",
    "type": "Feature",
    "runtime_helper": "109 min",
    "runtime_helper_2": "109min",
    "runtime": "1h 49min",
    "rating_1_10": null,
    "director_s": "Emilie Blichfeldt",
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Makeup and Hairstyling",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Ugly%20Stepsister",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Ugly%20Stepsister",
    "id": 31
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "If I Had Legs I'd Kick You",
    "type": "Feature",
    "runtime_helper": "114 min",
    "runtime_helper_2": "114min",
    "runtime": "1h 54min",
    "rating_1_10": null,
    "director_s": "Mary Bronstein",
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Actress in a Leading Role",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=If%20I%20Had%20Legs%20I%27d%20Kick%20You",
    "imdb_url": "https://www.imdb.com/find/?q=If%20I%20Had%20Legs%20I%27d%20Kick%20You",
    "id": 32
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Sir\u0101t",
    "type": "Feature",
    "runtime_helper": "114 min",
    "runtime_helper_2": "114min",
    "runtime": "1h 54min",
    "rating_1_10": null,
    "director_s": "\u00d3liver Laxe",
    "country": null,
    "nominations_number": 2,
    "nominated_categories": "International Feature Film; Sound",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Sir%C4%81t",
    "imdb_url": "https://www.imdb.com/find/?q=Sir%C4%81t",
    "id": 33
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Alabama Solution",
    "type": "Feature",
    "runtime_helper": "115 min",
    "runtime_helper_2": "115min",
    "runtime": "1h 55min",
    "rating_1_10": null,
    "director_s": "Andrew Jarecki",
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Documentary Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "HBO max",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Alabama%20Solution",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Alabama%20Solution",
    "id": 34
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Bugonia",
    "type": "Feature",
    "runtime_helper": "118 min",
    "runtime_helper_2": "118min",
    "runtime": "1h 58min",
    "rating_1_10": 7.0,
    "director_s": null,
    "country": null,
    "nominations_number": 4,
    "nominated_categories": "Actress in a Leading Role; Best Picture; Music (Original Score); Writing (Adapted Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Bugonia",
    "imdb_url": "https://www.imdb.com/find/?q=Bugonia",
    "id": 35
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Smashing Machine",
    "type": "Feature",
    "runtime_helper": "123 min",
    "runtime_helper_2": "123min",
    "runtime": "2h 03min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Makeup and Hairstyling",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "PirateBay",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Smashing%20Machine",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Smashing%20Machine",
    "id": 36
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Hamnet",
    "type": "Feature",
    "runtime_helper": "125 min",
    "runtime_helper_2": "125min",
    "runtime": "2h 05min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 8,
    "nominated_categories": "Actress in a Leading Role; Best Picture; Casting; Costume Design; Directing; Music (Original Score); Production Design; Writing (Adapted Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "PC",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Hamnet",
    "imdb_url": "https://www.imdb.com/find/?q=Hamnet",
    "id": 37
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Weapons",
    "type": "Feature",
    "runtime_helper": "128 min",
    "runtime_helper_2": "128min",
    "runtime": "2h 08min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Actress in a Supporting Role",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "HBO max",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Weapons",
    "imdb_url": "https://www.imdb.com/find/?q=Weapons",
    "id": 38
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Lost Bus",
    "type": "Feature",
    "runtime_helper": "130 min",
    "runtime_helper_2": "130min",
    "runtime": "2h 10min",
    "rating_1_10": null,
    "director_s": "Paul Greengrass",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Visual Effects",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "AppleTV",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Lost%20Bus",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Lost%20Bus",
    "id": 39
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Jurassic World Rebirth",
    "type": "Feature",
    "runtime_helper": "133 min",
    "runtime_helper_2": "133min",
    "runtime": "2h 13min",
    "rating_1_10": null,
    "director_s": "Gareth Edwards",
    "country": "United States",
    "nominations_number": 1,
    "nominated_categories": "Visual Effects",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "skySHOWTIME",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Jurassic%20World%20Rebirth",
    "imdb_url": "https://www.imdb.com/find/?q=Jurassic%20World%20Rebirth",
    "id": 40
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Sentimental Value",
    "type": "Feature",
    "runtime_helper": "133 min",
    "runtime_helper_2": "133min",
    "runtime": "2h 13min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 8,
    "nominated_categories": "Actor in a Supporting Role; Actress in a Leading Role; Actress in a Supporting Role; Best Picture; Directing; Film Editing; International Feature Film; Writing (Original Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Sentimental%20Value",
    "imdb_url": "https://www.imdb.com/find/?q=Sentimental%20Value",
    "id": 41
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "Sinners",
    "type": "Feature",
    "runtime_helper": "137 min",
    "runtime_helper_2": "137min",
    "runtime": "2h 17min",
    "rating_1_10": 7.0,
    "director_s": null,
    "country": null,
    "nominations_number": 16,
    "nominated_categories": "Actor in a Leading Role; Actor in a Supporting Role; Actress in a Supporting Role; Best Picture; Casting; Cinematography; Costume Design; Directing; Film Editing; Makeup and Hairstyling; Music (Original Score); Music (Original Song); Production Design; Sound; Visual Effects; Writing (Original Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Sinners",
    "imdb_url": "https://www.imdb.com/find/?q=Sinners",
    "id": 42
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Marty Supreme",
    "type": "Feature",
    "runtime_helper": "150 min",
    "runtime_helper_2": "150min",
    "runtime": "2h 30min",
    "rating_1_10": null,
    "director_s": "Josh Safdie",
    "country": "United States",
    "nominations_number": 9,
    "nominated_categories": "Actor in a Leading Role; Best Picture; Casting; Cinematography; Costume Design; Directing; Film Editing; Production Design; Writing (Original Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Marty%20Supreme",
    "imdb_url": "https://www.imdb.com/find/?q=Marty%20Supreme",
    "id": 43
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Frankenstein",
    "type": "Feature",
    "runtime_helper": "152 min",
    "runtime_helper_2": "152min",
    "runtime": "2h 32min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 9,
    "nominated_categories": "Actor in a Supporting Role; Best Picture; Cinematography; Costume Design; Makeup and Hairstyling; Music (Original Score); Production Design; Sound; Writing (Adapted Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Netflix",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Frankenstein",
    "imdb_url": "https://www.imdb.com/find/?q=Frankenstein",
    "id": 44
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "F1",
    "type": "Feature",
    "runtime_helper": "155 min",
    "runtime_helper_2": "155min",
    "runtime": "2h 35min",
    "rating_1_10": 7.0,
    "director_s": "Joseph Kosinski",
    "country": "United States",
    "nominations_number": 5,
    "nominated_categories": "Best Picture; Film Editing; Sound; Visual Effects",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/F1_(film)",
    "imdb_url": "https://www.imdb.com/title/tt1745960/",
    "id": 45
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "The Secret Agent",
    "type": "Feature",
    "runtime_helper": "158 min",
    "runtime_helper_2": "158min",
    "runtime": "2h 38min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 4,
    "nominated_categories": "Actor in a Leading Role; Best Picture; Casting; International Feature Film",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Secret%20Agent",
    "imdb_url": "https://www.imdb.com/find/?q=The%20Secret%20Agent",
    "id": 46
  },
  {
    "watched": true,
    "watched_date": null,
    "title": "One Battle after Another",
    "type": "Feature",
    "runtime_helper": "161 min",
    "runtime_helper_2": "161min",
    "runtime": "2h 41min",
    "rating_1_10": 6.0,
    "director_s": "Paul Thomas Anderson",
    "country": "United States",
    "nominations_number": 12,
    "nominated_categories": "Actor in a Leading Role; Actor in a Supporting Role; Actress in a Supporting Role; Best Picture; Casting; Cinematography; Directing; Film Editing; Music (Original Score); Production Design; Sound; Writing (Adapted Screenplay)",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=One%20Battle%20after%20Another",
    "imdb_url": "https://www.imdb.com/find/?q=One%20Battle%20after%20Another",
    "id": 47
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Song Sung Blue",
    "type": "Feature",
    "runtime_helper": "173 min",
    "runtime_helper_2": "173min",
    "runtime": "2h 53min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Actress in a Leading Role",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "PirateBay",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Song%20Sung%20Blue",
    "imdb_url": "https://www.imdb.com/find/?q=Song%20Sung%20Blue",
    "id": 48
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Kokuho",
    "type": "Feature",
    "runtime_helper": "174 min",
    "runtime_helper_2": "174min",
    "runtime": "2h 54min",
    "rating_1_10": null,
    "director_s": null,
    "country": null,
    "nominations_number": 1,
    "nominated_categories": "Makeup and Hairstyling",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": null,
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Kokuho",
    "imdb_url": "https://www.imdb.com/find/?q=Kokuho",
    "id": 49
  },
  {
    "watched": false,
    "watched_date": null,
    "title": "Avatar: Fire and Ash",
    "type": "Feature",
    "runtime_helper": "197 min",
    "runtime_helper_2": "197min",
    "runtime": "3h 17min",
    "rating_1_10": null,
    "director_s": "James Cameron",
    "country": "United States",
    "nominations_number": 2,
    "nominated_categories": "Costume Design; Visual Effects",
    "wikipedia_link": "Wikipedia",
    "imdb_link": "IMDb",
    "where_to_watch": "Theater",
    "notes": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Special:Search?search=Avatar%3A%20Fire%20and%20Ash",
    "imdb_url": "https://www.imdb.com/find/?q=Avatar%3A%20Fire%20and%20Ash",
    "id": 50
  }
];
